version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - dogsled
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - goconst
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - ireturn
    - makezero
    - misspell
    - mnd
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - usetesting
    - varnamelen
    - wastedassign
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - encoding/json.Marshal
        - encoding/json.MarshalIndent
    errchkjson:
      report-no-exported: true
    gosec:
      excludes:
        - G104
    govet:
      disable:
        - fieldalignment
      enable-all: true
    grouper:
      import-require-single-import: true
      import-require-grouping: true
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
    nolintlint:
      require-explanation: true
      require-specific: true
    predeclared:
      qualified-name: true
    revive:
      confidence: 0.8
      rules:
        - name: argument-limit
          arguments:
            - 4
          severity: warning
          disabled: false
        - name: atomic
          severity: warning
          disabled: false
        - name: blank-imports
          severity: warning
          disabled: false
        - name: bool-literal-in-expr
          severity: warning
          disabled: false
        - name: call-to-gc
          severity: warning
          disabled: false
        - name: confusing-naming
          severity: warning
          disabled: false
        - name: confusing-results
          severity: warning
          disabled: false
        - name: constant-logical-expr
          severity: warning
          disabled: false
        - name: context-as-argument
          severity: warning
          disabled: false
        - name: context-keys-type
          severity: warning
          disabled: false
        - name: deep-exit
          severity: warning
          disabled: false
        - name: defer
          arguments:
            - - call-chain
              - loop
              - method-call
              - recover
              - return
          severity: warning
          disabled: false
        - name: dot-imports
          severity: warning
          disabled: false
        - name: duplicated-imports
          severity: warning
          disabled: false
        - name: early-return
          severity: warning
          disabled: false
        - name: empty-block
          severity: warning
          disabled: false
        - name: empty-lines
          severity: warning
          disabled: false
        - name: error-naming
          severity: warning
          disabled: false
        - name: error-return
          severity: warning
          disabled: false
        - name: error-strings
          severity: warning
          disabled: false
        - name: errorf
          severity: warning
          disabled: false
        - name: exported
          arguments:
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
          severity: warning
          disabled: false
        - name: flag-parameter
          severity: warning
          disabled: true
        - name: function-result-limit
          arguments:
            - 3
          severity: warning
          disabled: false
        - name: get-return
          severity: warning
          disabled: false
        - name: identical-branches
          severity: warning
          disabled: false
        - name: if-return
          severity: warning
          disabled: false
        - name: increment-decrement
          severity: warning
          disabled: false
        - name: indent-error-flow
          severity: warning
          disabled: false
        - name: import-shadowing
          severity: warning
          disabled: false
        - name: modifies-parameter
          severity: warning
          disabled: false
        - name: nested-structs
          severity: warning
          disabled: false
        - name: optimize-operands-order
          severity: warning
          disabled: false
        - name: package-comments
          severity: warning
          disabled: false
        - name: range
          severity: warning
          disabled: false
        - name: range-val-in-closure
          severity: warning
          disabled: false
        - name: range-val-address
          severity: warning
          disabled: false
        - name: receiver-naming
          severity: warning
          disabled: false
        - name: redefines-builtin-id
          severity: warning
          disabled: false
        - name: string-of-int
          severity: warning
          disabled: false
        - name: struct-tag
          severity: warning
          disabled: false
        - name: superfluous-else
          severity: warning
          disabled: false
        - name: time-equal
          severity: warning
          disabled: false
        - name: time-naming
          severity: warning
          disabled: false
        - name: var-naming
          severity: warning
          disabled: false
        - name: var-declaration
          severity: warning
          disabled: false
        - name: unconditional-recursion
          severity: warning
          disabled: false
        - name: unexported-naming
          severity: warning
          disabled: false
        - name: unexported-return
          severity: warning
          disabled: false
        - name: unhandled-error
          arguments:
            - fmt.Printf
          severity: warning
          disabled: true
        - name: unnecessary-stmt
          severity: warning
          disabled: false
        - name: unreachable-code
          severity: warning
          disabled: false
        - name: unused-parameter
          severity: warning
          disabled: false
        - name: unused-receiver
          severity: warning
          disabled: false
        - name: useless-break
          severity: warning
          disabled: false
        - name: waitgroup-by-value
          severity: warning
          disabled: false
    staticcheck:
      checks:
        - all
    varnamelen:
      ignore-names:
        - err
        - id
      ignore-decls:
        - t testing.T
        - w http.ResponseWriter
        - r *http.Request
        - h http.Handler
  exclusions:
    generated: lax
    rules:
      - linters:
          - paralleltest
        text: does not use range value in test Run
      - linters:
          - goconst
        path: example_.*_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
    goimports:
      local-prefixes:
        - darlinggo.co
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
